# 9.2 가우시안 혼합

**가우시안 혼합 모델**은 샘플이 파라미터가 알려지지 않은 여러 개의 혼합된 가우시안 분포에서 생성되었다고 가정하는 확률 모델이다. 하나의 가우시안 분포에서 생성된 모든 샘플은 하나의 클러스터를 형성한다. 일반적으로 이 클러스터는 타원형이다.

가장 간단한 버전이 `GaussianMisture`클래스에 구현되어 있다. 여기서는 사전에 가우시안 분포의 개수 k를 알아야 한다.

In [3]:
import numpy as np
from sklearn.datasets import make_moons

X, y = make_moons(n_samples=1000,noise=0.05)

In [4]:
from sklearn.mixture import GaussianMixture

gm = GaussianMixture(n_components=3, n_init=10)
gm.fit(X)

GaussianMixture(n_components=3, n_init=10)

In [5]:
# 이 알고리즘이 추정한 파라미터 확인
gm.weights_

array([0.18766785, 0.20437814, 0.60795401])

In [6]:
gm.means_

array([[ 1.78164009, -0.02780011],
       [-0.73805591,  0.5584918 ],
       [ 0.51954568,  0.23141927]])

In [7]:
gm.covariances_

array([[[ 0.03826521,  0.05114605],
        [ 0.05114605,  0.08118337]],

       [[ 0.05365216,  0.06243521],
        [ 0.06243521,  0.08794177]],

       [[ 0.17935176, -0.11387794],
        [-0.11387794,  0.29599042]]])

이 클래스는 기댓값-최대화 알고리즘을 사용한다. 이 알고리즘은 k-평균 알고리즘과 공통점이 많다. 클러스터 파라미터를 랜덤하게 초기화하고 수렴할 때까지 두 단계를 반복한다.

1. 기댓값 단계: 샘플을 클러스터에 할당
2. 최대화 단계: 클러스터 업데이트

하지만 k-평균과 달리 EM은 하드 클러스터 할당이 아닌 소프트 클러스터 할당을 사용한다. 예를 들어 기댓값 단계에서 알고리즘은 각 클러스터에 속할 확률을 예측한다. 그다음 최대화 단계에서 각 클러스터가 데이터셋에 있는 모든 샘플을 사용해 업데이트된다. 클러스터에 속할 추정 확률로 샘플에 가중치가 적용된다. 이 확률을 샘플에 대한 클러스터의 책임이라고 한다.

In [8]:
# 알고리즘 수렴 여부
gm.converged_

True

In [9]:
# 반복 횟수
gm.n_iter_

17

하드 군집 위해서는 predict() 메서드를 사용하고 소프트 군집을 위해서는 predict_proba() 메서드를 사용한다.

In [11]:
gm.predict(X)

array([0, 2, 0, 2, 2, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 1, 1, 0, 1, 2, 2, 2,
       1, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 0, 2, 2, 2, 0, 0, 1, 1, 2, 0, 2, 1, 2, 0, 0, 2, 2, 1, 1, 1,
       2, 2, 1, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 0, 1, 1, 2, 1, 0, 2, 2, 2,
       2, 2, 0, 2, 2, 2, 1, 2, 0, 2, 2, 1, 2, 1, 2, 2, 0, 2, 1, 2, 2, 0,
       2, 2, 0, 2, 0, 2, 2, 1, 1, 1, 2, 0, 2, 2, 2, 1, 2, 0, 0, 1, 2, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 2, 0,
       0, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 1,
       2, 2, 1, 2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 0, 0, 0, 2, 2, 1, 2, 2, 0,
       2, 2, 2, 1, 2, 1, 1, 0, 2, 0, 2, 2, 0, 1, 1, 1, 2, 0, 0, 1, 2, 2,
       2, 1, 2, 0, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2,
       2, 1, 0, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2,
       2, 2, 0, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 0, 2, 2, 1, 0, 2, 2, 2, 0,
       1, 2, 0, 1, 1, 2, 0, 2, 0, 2, 2, 1, 2, 2, 2,

In [12]:
gm.predict_proba(X)

array([[9.99689157e-001, 2.88218145e-193, 3.10843044e-004],
       [4.11305441e-134, 1.22095320e-022, 1.00000000e+000],
       [9.99857394e-001, 2.61254027e-195, 1.42605860e-004],
       ...,
       [5.09121280e-130, 4.09246642e-024, 1.00000000e+000],
       [3.51877694e-018, 5.29188867e-123, 1.00000000e+000],
       [1.04785183e-267, 6.20692434e-001, 3.79307566e-001]])

가우시안 혼합 모델은 생성 모델이다. 즉 이 모델에서 새로운 샘플을 만들 수 있다.

In [13]:
X_new, y_new = gm.sample(6)
X_new

array([[-0.85192399,  0.42980903],
       [-0.62671934,  0.73054393],
       [ 0.09507912, -0.86403014],
       [ 0.90854595, -0.18751309],
       [ 1.06264251, -0.07110763],
       [-0.28893411,  1.3306598 ]])

In [14]:
y_new

array([1, 1, 2, 2, 2, 2])

`score_samples()`메서드 사용하여 주어진 위치에서 모델의 밀도 추정 가능. 샘플이 주어지면 이 메서드는 그 위치의 확률 밀도 함수의 로그를 예측한다.

In [15]:
# 모델의 밀도 추정
gm.score_samples(X)

array([-4.23066075e-01, -1.52894328e+00, -6.14248956e-01, -1.74904450e+00,
       -2.23936986e+00, -2.67070245e-01, -1.80705694e-02, -1.64882950e+00,
       -8.61820603e-01, -9.74638628e-01, -1.14277229e+00, -1.43950605e+00,
       -1.70704845e+00, -2.71438129e+00, -1.62630381e+00, -7.18847101e-01,
       -7.02277979e-01, -1.26352917e+00,  3.13713426e-03, -1.37218643e+00,
       -1.42082942e+00, -1.51822898e+00, -4.86850978e-01, -8.28741289e-01,
       -1.72752931e+00, -1.28897233e+00, -1.63856696e+00, -1.63493507e+00,
       -1.67222474e+00, -1.70794078e+00, -1.31096335e+00, -1.64163335e+00,
       -1.77615459e+00, -1.40947884e+00, -1.43189338e+00, -1.05338361e+00,
       -1.87091165e+00, -1.57695398e+00, -1.77697324e+00, -1.69899250e+00,
       -1.61084918e+00, -1.77142955e+00, -1.76159704e+00, -1.91664259e+00,
       -2.22107686e+00, -6.53132841e-01, -5.19829144e-01, -1.57703878e+00,
       -2.02433406e+00, -1.15694309e+00, -2.50448252e+00, -8.62889583e-02,
       -8.87815512e-01, -

특성이나 클러스터가 많거나 샘플이 적을 때는 EM이 최적의 솔루션으로 수렴하기 어렵다. 어려움을 줄이려면 알고리즘이 학습할 파라미터 개수를 제한해야 한다. 이 방법 중 하나는 클러스터의 모양과 방향의 범위를 제한하는 것이다.

`covariance_type`
- spherical: 모든 클러스터가 원형이지만 지름은 다를 수 있다.
- diag: 클러스터는 크기에 상관없이 어떤 타원형도 가능하다. 하지만 타원의 축은 좌표 축과 나란해야 한다.
- tied: 모든 클러스터가 동일한 타원 모양, 크기, 방향 가진다.

## 9.2.1 가우시안 혼합을 사용한 이상치 탐지

이상치 탐지는 보통과 많이 다른 샘플을 감지하는 작업이다. 가우시안 혼합 모델을 이상치 탐지에 사용하는 방법은 밀도가 낮은 지역에 있는 모든 샘플을 이상치로 보는 것이다. 이를 위해서는 밀도 임곗값을 정해야 한다.

In [16]:
densities = gm.score_samples(X)
density_threshold = np.percentile(densities, 4)
anomalies = X[densities < density_threshold]

이와 비슷한 작업은 특이치 탐지다. 이 알고리즘은 이상치로 오염되지 않은 깨끗한 데이터셋에서 훈련한다는 것이 이상치 탐지와 다르다. 이상치 탐지는 이런 가정을 하지 않는다. 실제로 이상치 탐지는 데이터셋을 정제하는 데 자주 사용된다.

## 9.2.2 클러스터 개수 선택하기

k-평균에서는 이너셔나 실루엣 점수를 사용해 적절한 클러스터 개수를 사용한다. 가우시안 혼합에서는 이런 지표를 사용할 수 없다. 이런 지표들은 클러스터가 타원형이거나 크기가 다를 때 안정적이지 않기 때문이다. 대신 정의된 BIC나 AIC와 같은 이론적 정보 기준을 최소화하는 모델을 찾는다.

BIC, AIC는 모두 학습할 파라미터가 많은 모델에게 벌칙을 가하고 데이터에 잘 학습하는 모델에게 보상을 더한다. 이 둘은 종종 동일한 모델을 선택한다. 둘의 선택이 다를 경우 BIC가 선택한 모델이 AIC가 선택한 모델보다 간단한 경향이 있다.

In [17]:
gm.bic(X)

np.float64(2720.4127684785867)

In [18]:
gm.aic(X)

np.float64(2636.9809287358903)

## 9.2.3 베이즈 가우시안 혼합 모델

최적의 클러스터 개수를 수동으로 찾지 않고 불필요한 클러스터의 가중치를 0으로 만드는 `BayesianGaussianMixture` 클래스를 사용할 수 있다. 클러스터 개수 n_components를 최적의 클러스터 개수보다 크다고 믿을 만한 값으로 지정한다. 이 알고리즘은 자동으로 불필요한 클러스터를 제거한다.

In [19]:
from sklearn.mixture import BayesianGaussianMixture

bgm = BayesianGaussianMixture(n_components=10, n_init=10)
bgm.fit(X)
np.round(bgm.weights_, 2)

array([0.17, 0.09, 0.14, 0.2 , 0.12, 0.16, 0.12, 0.  , 0.  , 0.  ])

알고리즘이 자동으로 3개의 클러스터가 필요하다는 것을 감지했다. 이 모델에서 클러스터 파라미터는 더는 고정된 모델 파라미터가 아니라 클러스터 할당처럼 잠재 확률 변수로 취급된다. 따라서 이제 z는 클러스터 파라미터와 클러스터 할당을 모두 포함한다.

베타 분포는 고정 범위 안에 놓인 값을 가진 확률 변수를 모델링할 때 자주 사용된다. 이 경우는 0~1 범위다. 이 프로세스는 새로운 샘플이 작은 클러스터보다 큰 클러스터에 합류할 가능성이 높은 데이터셋에 잘 맞는 모델이다.

잠재 변수에 대한 사전 지식이 사전 확률이라는 확률 분포에 인코딩될 수 있다. 클러스터 개수에 대한 사전 믿음은 weight_concentration_prior 매개변수를 사용해 조정할 수 있다.

베이즈 정리는 데이터를 관측하고 난 후 잠재 변수에 대한 확률 분포를 업데이트하는 방법을 설명한다. 이는 X가 주어졌을 때 z의 조건부 확률인 사후 확률 분포를 계산한다.

## 9.2.4 이상치 탐지와 특이치 탐지를 위한 다른 알고리즘

- PCA: 간단하고 매우 효과적인 이상치 탐지 기법
- Fast-MCD: EllipticEnvelope 클래스에서 구현됨. 이상치 감지에 유용. 보통 데이터셋을 정제할 때 사용됨.
- 아이솔레이션 포레스트: 고차원 데이터셋에서 이상치 감지를 위한 효율적인 알고리즘. 이 알고리즘은 무작위로 성장한 결정 트리로 구성된 랜덤 포레스트를 만든다.
- LOF: 주어진 샘플 주위의 밀도와 이웃 주위의 밀도를 비교한다. 이상치 탐지에 좋음.
- one-class SVM: 특이치 탐지에 잘 맞음.